// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnyepdtuzsntqgaefxmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNueWVwZHR1enNudHFnYWVmeG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzkwOTEsImV4cCI6MjA2MjExNTA5MX0.lNzUe8gWwCWphVJUhroCBA436KYcY-MD_tHtqxoukIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);